matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - language: rust
      # We use OSX so that we can get a reasonably up to date version of SQLCipher.
      # (The version in Travis's default Ubuntu Trusty is much too old).
      os: osx
      before_install:
        - brew install sqlcipher --with-fts
      rust: 1.25.0  # Must align with `build/version.rs`.
      script:
        - ./scripts/cargo_test.sh
      cache: cargo
    - language: rust
      # We use OSX so that we can get a reasonably up to date version of SQLCipher.
      # (The version in Travis's default Ubuntu Trusty is much too old).
      os: osx
      before_install:
        - brew install sqlcipher --with-fts
      rust: stable
      script:
        - ./scripts/cargo_test.sh
      cache: cargo
    - language: rust
      # We use OSX so that we can get a reasonably up to date version of SQLCipher.
      # (The version in Travis's default Ubuntu Trusty is much too old).
      os: osx
      before_install:
        - brew install sqlcipher --with-fts
      rust: beta
      script:
        - ./scripts/cargo_test.sh
      cache: cargo
    - language: rust
      # We use OSX so that we can get a reasonably up to date version of SQLCipher.
      # (The version in Travis's default Ubuntu Trusty is much too old).
      os: osx
      before_install:
        - brew install sqlcipher --with-fts
      rust: nightly
      script:
        - ./scripts/cargo_test.sh
      cache: cargo
